### ISSUE TITLE
[BUG] jdk 1.8导出文件内容为空

### ISSUE THREAD

**Issue by NHPT** [wgpsec/fofa_viewer#157]
**描述你遇到的问题**
结果导出为空

**复现步骤**

**屏幕截图**

![image](https://github.com/user-attachments/assets/6bfd7def-f07c-4f90-9928-93e87d87c3e2)
![image](https://github.com/user-attachments/assets/a85192fd-9e76-4604-982c-14e61a213202)
![image](https://github.com/user-attachments/assets/35a90fc1-540e-4b40-8c7d-8994f20bf6e8)
**运行环境**
 - 操作系统 
   
Windows 11
 - Java 版本 
   
 - 软件版本 
   
java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.371-b11, mixed mode)
**补充说明**

**Comment by keac** [comment]
请命令行运行 java -jar 查看是否有报错日志

**Comment by Kiand1** [comment]
一样的问题
控制台报错
` ERROR MainController.java.java:529-call:
java.lang.NullPointerException
        at org.fofaviewer.utils.DataUtil.loadJsonData(DataUtil.java:123)
        at org.fofaviewer.controllers.MainController$7.call(MainController.java:508)
        at org.fofaviewer.controllers.MainController$7.call(MainController.java:494)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...`

**Comment by 0xShe** [comment]
俺也一样

**Comment by Mr-xn** [comment]
@NHPT @0xShe @Kiand1 
可能是分页的问题，尝试不导出整数页数据 比如查询结果显示有10页（假设每页100条数据，实际是912条，导出数据10页就可能报空指针错误） 导出9页 试试

**Comment by 0xShe** [comment]
还是空 所以能修复一下吗 好兄弟

**Comment by jnabnsn** [comment]
在org.fofaviewer.controllers.MainController#exportAction的498行左右，对bean.next重新初始化一下就行了。
![image](https://github.com/user-attachments/assets/bab7c0b6-8cc5-42b9-8c59-5a173b7e69ec)

**Comment by Ly4j** [comment]
什么时候修复这个问题
