### ISSUE TITLE
师傅这是啥报错，我java版本不对吗？

### ISSUE THREAD

**Issue by Hatcat123** [wgpsec/fofa_viewer#21]
一闪而过
```
C:\0个人\sec\01信息收集\fofa\fofaviewer_1.0.7_>java -jar fofaviewer.jar
Exception in Application start method
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/skin/TextFieldSkin
        at org.controlsfx.control.textfield.CustomTextField.createDefaultSkin(CustomTextField.java:161)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9513)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9506)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9506)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9506)
        at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:583)
        at javafx.graphics/javafx.scene.Scene.access$3500(Scene.java:173)
        at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2502)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:410)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:409)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:436)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:473)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:372)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:945)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:973)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/skin/TextFieldSkin
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        at org.controlsfx.control.textfield.CustomTextField.createDefaultSkin(CustomTextField.java:161)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1419)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1419)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1419)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9513)
        at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:583)
        at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1770)
        at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:394)
        at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
        at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1098)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
        at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1186)
        at javafx.graphics/javafx.stage.Window.show(Window.java:1201)
        at javafx.graphics/javafx.stage.Stage.show(Stage.java:276)
        at org.fofaviewer.main.MainApp.start(MainApp.java:21)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.scene.control.skin.TextFieldSkin
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 60 more
Exception running application org.fofaviewer.main.MainApp
```

**Comment by f1ashine** [comment]
是用的java8吗

**Comment by misare** [comment]
JDK11 该如何启动它

**Comment by keac** [comment]
最新版本已兼任JDK以及更高版本
