### ISSUE TITLE
JDK1.8 情况下出现 SSLExption

### ISSUE THREAD

**Issue by Jfirm** [wgpsec/fofa_viewer#38]
![image](https://user-images.githubusercontent.com/40061336/137686174-28c83453-8433-4162-b4cb-2d8c238f37d3.png)

**Comment by Jfirm** [comment]
error.log

十月 18, 2021 3:20:43 下午 org.fofaviewer.utils.LogUtil log
警告: javax.net.ssl.SSLException: Received fatal alert: internal_error
me.gv7.woodpecker.requests.exception.RequestsException: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.doRequest(URLConnectionExecutor.java:194)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.proceed(URLConnectionExecutor.java:46)
	at me.gv7.woodpecker.requests.InterceptorChain.proceed(InterceptorChain.java:22)
	at me.gv7.woodpecker.requests.RequestBuilder.send(RequestBuilder.java:493)
	at org.fofaviewer.utils.RequestHelper.getHTML(RequestHelper.java:60)
	at org.fofaviewer.controls.RequestTask.call(RequestTask.java:21)
	at org.fofaviewer.controls.RequestTask.call(RequestTask.java:8)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.doRequest(URLConnectionExecutor.java:192)
	... 9 more

十月 18, 2021 3:22:41 下午 org.fofaviewer.utils.LogUtil log
警告: javax.net.ssl.SSLException: Received fatal alert: internal_error
me.gv7.woodpecker.requests.exception.RequestsException: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.doRequest(URLConnectionExecutor.java:194)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.proceed(URLConnectionExecutor.java:46)
	at me.gv7.woodpecker.requests.InterceptorChain.proceed(InterceptorChain.java:22)
	at me.gv7.woodpecker.requests.RequestBuilder.send(RequestBuilder.java:493)
	at org.fofaviewer.utils.RequestHelper.getHTML(RequestHelper.java:60)
	at org.fofaviewer.controls.RequestTask.call(RequestTask.java:21)
	at org.fofaviewer.controls.RequestTask.call(RequestTask.java:8)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.doRequest(URLConnectionExecutor.java:192)
	... 9 more

十月 18, 2021 3:23:39 下午 org.fofaviewer.utils.LogUtil log
警告: javax.net.ssl.SSLException: Received fatal alert: internal_error
me.gv7.woodpecker.requests.exception.RequestsException: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.doRequest(URLConnectionExecutor.java:194)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.proceed(URLConnectionExecutor.java:46)
	at me.gv7.woodpecker.requests.InterceptorChain.proceed(InterceptorChain.java:22)
	at me.gv7.woodpecker.requests.RequestBuilder.send(RequestBuilder.java:493)
	at org.fofaviewer.utils.RequestHelper.getHTML(RequestHelper.java:60)
	at org.fofaviewer.controls.RequestTask.call(RequestTask.java:21)
	at org.fofaviewer.controls.RequestTask.call(RequestTask.java:8)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.doRequest(URLConnectionExecutor.java:192)
	... 9 more

十月 18, 2021 5:29:38 下午 org.fofaviewer.utils.LogUtil log
警告: javax.net.ssl.SSLException: Received fatal alert: internal_error
me.gv7.woodpecker.requests.exception.RequestsException: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.doRequest(URLConnectionExecutor.java:194)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.proceed(URLConnectionExecutor.java:46)
	at me.gv7.woodpecker.requests.InterceptorChain.proceed(InterceptorChain.java:22)
	at me.gv7.woodpecker.requests.RequestBuilder.send(RequestBuilder.java:493)
	at org.fofaviewer.utils.RequestHelper.getHTML(RequestHelper.java:60)
	at org.fofaviewer.controls.RequestTask.call(RequestTask.java:21)
	at org.fofaviewer.controls.RequestTask.call(RequestTask.java:8)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.doRequest(URLConnectionExecutor.java:192)
	... 9 more

十月 18, 2021 5:40:19 下午 org.fofaviewer.utils.LogUtil log
警告: javax.net.ssl.SSLException: Received fatal alert: internal_error
me.gv7.woodpecker.requests.exception.RequestsException: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.doRequest(URLConnectionExecutor.java:194)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.proceed(URLConnectionExecutor.java:46)
	at me.gv7.woodpecker.requests.InterceptorChain.proceed(InterceptorChain.java:22)
	at me.gv7.woodpecker.requests.RequestBuilder.send(RequestBuilder.java:493)
	at org.fofaviewer.utils.RequestHelper.getHTML(RequestHelper.java:60)
	at org.fofaviewer.controls.RequestTask.call(RequestTask.java:21)
	at org.fofaviewer.controls.RequestTask.call(RequestTask.java:8)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.doRequest(URLConnectionExecutor.java:192)
	... 9 more

**Comment by 052412** [comment]
超时时常如何配置
