### ISSUE TITLE
查询失败

### ISSUE THREAD

**Issue by x1aochuan** [wgpsec/fofa_viewer#69]
**描述你遇到的问题**
查询获取不到数据

**复现步骤**
出现问题前进行的操作：
通过查询 title="XXX", header="XXX", domain="xxx:"
获取不到数据，或者程序报错

**预期行为**

**屏幕截图**
![image](https://user-images.githubusercontent.com/97670155/151496778-07b8664a-07a7-4b38-9503-d25cdd41334e.png)

**运行环境**
 /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home/bin/java -jar fofaviewer.jar
![image](https://user-images.githubusercontent.com/97670155/151497255-88eab913-0cec-46a3-aaf6-afd0c601b310.png)

**补充说明**
`
2022-01-28 14:12:27.121 java[24508:4668935] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
2022-01-28 14:12:53.994 WARN RequestUtil.java.java:65-getHTML:
me.gv7.woodpecker.requests.exception.RequestsException: java.net.SocketTimeoutException: Read timed out
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.doRequest(URLConnectionExecutor.java:205)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.proceed(URLConnectionExecutor.java:46)
	at me.gv7.woodpecker.requests.InterceptorChain.proceed(InterceptorChain.java:22)
	at me.gv7.woodpecker.requests.RequestBuilder.send(RequestBuilder.java:493)
	at org.fofaviewer.utils.RequestUtil.getHTML(RequestUtil.java:63)
	at org.fofaviewer.request.Request.lambda$query$5(Request.java:53)
	at org.fofaviewer.request.Request.query(Request.java:111)
	at org.fofaviewer.request.Request.launchRequest(Request.java:104)
	at org.fofaviewer.request.Request.lambda$query$6(Request.java:49)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.getResponse(URLConnectionExecutor.java:218)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.doRequest(URLConnectionExecutor.java:202)
	... 13 more
2022-01-28 14:13:20.226 WARN RequestUtil.java.java:65-getHTML:
me.gv7.woodpecker.requests.exception.RequestsException: java.net.SocketTimeoutException: Read timed out
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.doRequest(URLConnectionExecutor.java:205)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.proceed(URLConnectionExecutor.java:46)
	at me.gv7.woodpecker.requests.InterceptorChain.proceed(InterceptorChain.java:22)
	at me.gv7.woodpecker.requests.RequestBuilder.send(RequestBuilder.java:493)
	at org.fofaviewer.utils.RequestUtil.getHTML(RequestUtil.java:63)
	at org.fofaviewer.request.Request.lambda$query$5(Request.java:53)
	at org.fofaviewer.request.Request.query(Request.java:111)
	at org.fofaviewer.request.Request.launchRequest(Request.java:104)
	at org.fofaviewer.request.Request.lambda$query$6(Request.java:49)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.getResponse(URLConnectionExecutor.java:218)
	at me.gv7.woodpecker.requests.executor.URLConnectionExecutor.doRequest(URLConnectionExecutor.java:202)
`

**Comment by diauweb** [comment]
提供一下你的主程序版本？

**Comment by keac** [comment]
请检查是否可以正常访问fofa api，尝试其他关键词是否可以搜索

**Comment by f1ashine** [comment]
网络访问超时，可自行更换网络解决。
