### ISSUE TITLE
[BUG] 对 macOS/aarch64-darwin 支持

### ISSUE THREAD

**Issue by 1oa** [wgpsec/fofa_viewer#83]
**描述你遇到的问题**

```
v@vdeMacBook-Air FofaViewer_1.1.6 % java -jar fofaviewer.jar 
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/v/.openjfx/cache/11/libprism_es2.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/v/.openjfx/cache/11/libprism_es2.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:214)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:194)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:135)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:53)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:69)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:51)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:833)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/v/.openjfx/cache/11/libprism_sw.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/v/.openjfx/cache/11/libprism_sw.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:214)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:194)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:135)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:53)
	at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:42)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:41)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:833)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:273)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
**复现步骤**

**预期行为**

**屏幕截图**

**运行环境**
 - 操作系统 
m1 bigsur
 - Java 版本 
   java version "17.0.2" 2022-01-18 LTS
 - 软件版本 

**补充说明**

**Comment by keac** [comment]
请问运行的是JDK11的包吗

**Comment by 1oa** [comment]
> 请问运行的是JDK11的包吗

是的

**Comment by DBUG-DBUG** [comment]
在m1芯片的macos monterey（java version "17.0.2" 2022-01-18 LTS）上也有同样的问题

**Comment by DBUG-DBUG** [comment]
> > 请问运行的是JDK11的包吗
> 
> 是的

如果您有时间可以尝试我在Macos上打包的app
传输链接：https://cowtransfer.com/s/745cd9324b9e47 传输口令：2fti8g

**Comment by keac** [comment]
看到使用的是JDK17环境，建议降级至16及以下尝试

**Comment by DBUG-DBUG** [comment]
猜测可能是JavaFX的原因？

**Comment by DBUG-DBUG** [comment]
JDk17不包含7avaFX环境，Java11以后的版本不再集成JavaFX

**Comment by DBUG-DBUG** [comment]
JDk17不包含JavaFX环境，Java11以后的版本不再集成JavaFX

**Comment by DBUG-DBUG** [comment]
已经打包有JavaFX环境的JDk，Macos上的app
传输链接：https://cowtransfer.com/s/745cd9324b9e47 传输口令：2fti8g

**Comment by Jerry-Swift** [comment]
> 已经打包有JavaFX环境的JDk，Macos上的app 传输链接：https://cowtransfer.com/s/745cd9324b9e47 传输口令：2fti8g

密码不正确

**Comment by dreamfly-jiefa** [comment]
> 



> 已经打包有JavaFX环境的JDk，Macos上的app 传输链接：https://cowtransfer.com/s/745cd9324b9e47 传输口令：2fti8g

有没有dmg的密码，谢谢
